// ============================================================
// VEGA SENTINEL - MODEL PARAMETERS (AUTO-GENERATED HEADER)
// ============================================================
// Generated by: ml/deployment/export_model_to_cpp.py
// Do not edit by hand - regenerate after retraining.
//
// Model: logistic_regression
// Trained on: dataset\processed\sentinel_window_features_v3.csv
//   107 windows (100 normal / 7 abnormal) - DEVELOPMENT DATASET, not final
//
// Feature order (must match firmware computation order):
//   0: humidity_mean
//   1: temp_mean
//   2: mq2_range
//   3: mq2_delta
//   4: mq2_std
//   5: humidity_std
//   6: flame_fraction
// ============================================================

#ifndef VEGA_SENTINEL_MODEL_H
#define VEGA_SENTINEL_MODEL_H

// -------- StandardScaler: feature means --------
const float MODEL_MEANS[7] = {
    73.242897f,   // humidity_mean
    28.448692f,   // temp_mean
    11.616822f,   // mq2_range
    0.485981f,   // mq2_delta
    3.734761f,   // mq2_std
    0.115325f,   // humidity_std
    0.004673f,   // flame_fraction
};

// -------- StandardScaler: feature scales --------
const float MODEL_SCALES[7] = {
    1.548508f,   // humidity_mean
    0.203029f,   // temp_mean
    17.851226f,   // mq2_range
    14.173402f,   // mq2_delta
    5.900505f,   // mq2_std
    0.163725f,   // humidity_std
    0.031721f,   // flame_fraction
};

// -------- Logistic regression --------
const float MODEL_COEFFS[7] = {
    -2.610233f,   // humidity_mean
    +0.422538f,   // temp_mean
    +0.384768f,   // mq2_range
    -0.322069f,   // mq2_delta
    -0.751392f,   // mq2_std
    +0.561356f,   // humidity_std
    +0.890513f,   // flame_fraction
};

const float MODEL_INTERCEPT = -3.483560f;

// Decision threshold: FIXED at 0.5.
// Do NOT tune this to force a demonstration to succeed.
const float MODEL_THRESHOLD = 0.5f;

// Number of model input features
const int MODEL_NUM_FEATURES = 7;

#endif // VEGA_SENTINEL_MODEL_H
