"""VEGA Sentinel - export trained model constants to a C++ header.

Reads the JSON produced by ml/training/train_model.py and regenerates
firmware/sentinel_final/sentinel_final/model.h. Also verifies the export
by scoring the two reference windows from the Model A verification test
(normal window -> p ~ 0.018949, abnormal window -> p ~ 0.992752).

Usage (from repository root):
    python ml/training/train_model.py        # produces model_a_constants.json
    python ml/deployment/export_model_to_cpp.py
"""
import argparse
import json
import math
import os

DEFAULT_JSON = os.path.join("results", "model_results", "model_a_constants.json")
DEFAULT_HEADER = os.path.join(
    "firmware", "sentinel_final", "sentinel_final", "model.h"
)

HEADER_TEMPLATE = """// ============================================================
// VEGA SENTINEL - MODEL PARAMETERS (AUTO-GENERATED HEADER)
// ============================================================
// Generated by: ml/deployment/export_model_to_cpp.py
// Do not edit by hand - regenerate after retraining.
//
// Model: {model_type}
// Trained on: {trained_on}
//   {windows_total} windows ({windows_normal} normal / {windows_abnormal} abnormal) - {status}
//
// Feature order (must match firmware computation order):
{feature_comments}
// ============================================================

#ifndef VEGA_SENTINEL_MODEL_H
#define VEGA_SENTINEL_MODEL_H

// -------- StandardScaler: feature means --------
const float MODEL_MEANS[{n}] = {{
{mean_lines}
}};

// -------- StandardScaler: feature scales --------
const float MODEL_SCALES[{n}] = {{
{scale_lines}
}};

// -------- Logistic regression --------
const float MODEL_COEFFS[{n}] = {{
{coef_lines}
}};

const float MODEL_INTERCEPT = {intercept:.6f}f;

// Decision threshold: FIXED at 0.5.
// Do NOT tune this to force a demonstration to succeed.
const float MODEL_THRESHOLD = {threshold:.1f}f;

// Number of model input features
const int MODEL_NUM_FEATURES = {n};

#endif // VEGA_SENTINEL_MODEL_H
"""

# Reference windows used to verify the export (from the Model A
# on-ARIES verification; expected p values are documented results)
REFERENCE_NORMAL = [73.5, 28.5, 10.0, 1.0, 3.0, 0.10, 0.0]
REFERENCE_ABNORMAL = [69.8, 28.2, 34.0, -14.0, 10.0, 0.24, 0.10]
EXPECTED_NORMAL_P = 0.018949
EXPECTED_ABNORMAL_P = 0.992752


def predict(consts, features):
    """Mirror of the firmware inference: standardise + score + sigmoid."""
    score = consts["intercept"]
    for i in range(len(consts["coefficients"])):
        z = (features[i] - consts["scaler_mean"][i]) / consts["scaler_scale"][i]
        score += consts["coefficients"][i] * z
    if score > 30:
        return 1.0
    if score < -30:
        return 0.0
    return 1.0 / (1.0 + math.exp(-score))


def main():
    parser = argparse.ArgumentParser(
        description="Export Model A constants to the firmware model.h"
    )
    parser.add_argument(
        "--json",
        default=DEFAULT_JSON,
        help=f"Model constants JSON (default: {DEFAULT_JSON})",
    )
    parser.add_argument(
        "--header",
        default=DEFAULT_HEADER,
        help=f"Output header path (default: {DEFAULT_HEADER})",
    )
    args = parser.parse_args()

    with open(args.json, "r", encoding="utf-8") as f:
        consts = json.load(f)

    features = consts["feature_order"]
    n = len(features)

    feature_comments = "\n".join(
        f"//   {i}: {name}" for i, name in enumerate(features)
    )

    def array_lines(values, fmt):
        """Format a float array: comma after the value, before the comment.

        Produces e.g.:
            73.242897f,   // humidity_mean
        (A trailing comma after the comment would end up inside the
        comment and break compilation.)
        """
        lines = []
        for value, name in zip(values, features):
            lines.append(f"    {fmt(value)},   // {name}")
        return "\n".join(lines)

    mean_lines = array_lines(consts["scaler_mean"], lambda v: f"{v:.6f}f")
    scale_lines = array_lines(consts["scaler_scale"], lambda v: f"{v:.6f}f")
    coef_lines = array_lines(consts["coefficients"], lambda v: f"{v:+.6f}f")

    header = HEADER_TEMPLATE.format(
        model_type=consts["model_type"],
        trained_on=consts["trained_on"],
        windows_total=consts["windows_total"],
        windows_normal=consts["windows_normal"],
        windows_abnormal=consts["windows_abnormal"],
        status="DEVELOPMENT DATASET, not final"
        if "DEVELOPMENT" not in consts.get("trained_on", "")
        else consts["trained_on"],
        feature_comments=feature_comments,
        n=n,
        mean_lines=mean_lines,
        scale_lines=scale_lines,
        coef_lines=coef_lines,
        intercept=consts["intercept"],
        threshold=consts.get("threshold", 0.5),
    )

    # ----------------------------------------------------------
    # Verify the export before writing anything
    # ----------------------------------------------------------
    if n != len(REFERENCE_NORMAL):
        raise SystemExit(
            f"Feature count mismatch: model has {n} features but the "
            f"reference verification windows have "
            f"{len(REFERENCE_NORMAL)}."
        )

    p_normal = predict(consts, REFERENCE_NORMAL)
    p_abnormal = predict(consts, REFERENCE_ABNORMAL)

    print("=" * 60)
    print("VEGA SENTINEL - C++ EXPORT VERIFICATION")
    print("=" * 60)
    print(f"Reference normal window  : p = {p_normal:.6f} "
          f"(expected ~{EXPECTED_NORMAL_P}) -> "
          f"{'NORMAL' if p_normal < 0.5 else 'ABNORMAL'}")
    print(f"Reference abnormal window : p = {p_abnormal:.6f} "
          f"(expected ~{EXPECTED_ABNORMAL_P}) -> "
          f"{'ABNORMAL' if p_abnormal >= 0.5 else 'NORMAL'}")

    tolerance = 0.01
    ok_normal = abs(p_normal - EXPECTED_NORMAL_P) < tolerance
    ok_abnormal = abs(p_abnormal - EXPECTED_ABNORMAL_P) < tolerance

    if not (ok_normal and ok_abnormal):
        raise SystemExit(
            "\nERROR: exported constants do not reproduce the reference "
            "probabilities. The model has changed - update the reference "
            "windows/expected values after validating the new model, or "
            "verify you exported the intended constants."
        )

    print("Reference probabilities reproduced - export verified.")

    # ----------------------------------------------------------
    # Write header
    # ----------------------------------------------------------
    os.makedirs(os.path.dirname(args.header), exist_ok=True)
    with open(args.header, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)

    print(f"\nHeader written: {args.header}")
    print("Remember: model.h is auto-generated - never hand-edit it.")


if __name__ == "__main__":
    main()
